fix = true
unsafe-fixes = true

exclude = [".venv", "build", "dist"]

line-length = 80
indent-width = 4

[lint]
select = [
    "F",
    "E",
    "W",
    "C901",
    "I001",
    "I002",
    "N",
    "D",
    "U",
    "YTT",
    "ANN",
    "S",
    "BLE001",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "EM",
    "EXE",
    "FA",
    "ISC",
    "ICN",
    "LOG",
    "G",
    "INP",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF001",
    "SLOT",
    "SIM",
    "TCH",
    "INT",
    "ARG",
    "TD004",
    "TD005",
    "TD006",
    "TD007",
    "PD",
    "PGH003",
    "PGH004",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "TRY",
    "FLY002",
    "NPY",
    "FAST",
    "AIR",
    "PERF",
    "FURB",
    "DOC",
    "RUF",
]
ignore = [
    "F405",
    "E115",
    "E999",    # deprecated
    "N813",
    "N814",
    "D105",
    "D107",
    "D200",
    "D202",
    "D203",
    "D205",
    "D212",
    "D301",
    "D400",
    "D401",
    "D412",
    "D413",
    "D415",
    "D416",
    "D418",
    "UP015",
    "ANN101",  # deprecated
    "ANN102",  # deprecated
    "ANN401",
    "S112",
    "S311",
    "S404",
    "B024",
    "EM101",
    "FURB101",
    "FURB103",
    "FURB110",
    "FURB140",
    "FURB148",
    "FURB181",
    "RUF020",
]

fixable = ["ALL"]

[lint.isort]
force-single-line = true
required-imports = ["from __future__ import annotations"]

[format]
quote-style = "double"
indent-style = "space"
line-ending = "lf"

docstring-code-format = true
docstring-code-line-length = "dynamic"
